"""added todoist_task_url to mesages

Revision ID: 01ebb96adcd6
Revises: 448be9032b0b
Create Date: 2025-01-26 03:15:02.940472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ebb96adcd6'
down_revision: Union[str, None] = '448be9032b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('todoist_task_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'todoist_task_url')
    # ### end Alembic commands ###
