"""message ondelete='CASCADE' added to foregin keys

Revision ID: d87ae97dd1df
Revises: 01ebb96adcd6
Create Date: 2025-01-26 16:17:49.582992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87ae97dd1df'
down_revision: Union[str, None] = '01ebb96adcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('fk_messages_sender_id', 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_messages_conversation_id', 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_conversation_id', 'messages', type_='foreignkey')
    op.drop_constraint('fk_messages_sender_id', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
